In [1]:
import numpy as onp
from pathlib import Path

import sys

sys.path.append("/home/florian/PhD/work/code/msm_for_nn/")

from msmfornn.wrapper import MSMCalculator

In [2]:
length = 10.
max_gridlevel = 4
level_one_gridspacing = 1.25
alpha = 3.0
level_zero_cutoff = alpha * level_one_gridspacing

p = 8
mu = 3

In [3]:
initialization_params = {
    'min_pos': onp.array([0.]),
    'max_pos': onp.array([length]),
    'level_one_gridspacing': level_one_gridspacing,
    'level_zero_cutoff': level_zero_cutoff,
    'max_gridlevel': max_gridlevel,
    'p': p,
    'mu': 3
}

In [4]:
msmcalculator = MSMCalculator(**initialization_params)

In [5]:
msmcalculator.kernelstencils

[None,
 array([ 1.90563553, -0.59641612,  0.27036583, -0.00397153, -0.20900143,
         0.23053501, -0.1059607 ,  0.01145449]),
 array([ 0.95281777, -0.29820806,  0.13518292, -0.00198577, -0.10450071,
         0.11526751, -0.05298035,  0.00572724]),
 array([ 0.47640888, -0.14910403,  0.06759146, -0.00099288, -0.05225036,
         0.05763375, -0.02649018,  0.00286362]),
 array([ 0.29636752, -0.02148983,  0.07519682,  0.02942644, -0.00318917,
         0.04806057,  0.00286904,  0.01549535,  0.01280209,  0.01087494])]

In [6]:
stencils = {str(lvl): stencil for lvl, stencil in enumerate(msmcalculator.kernelstencils) if stencil is not None}

In [7]:
onp.savez("precomputed_kernelstencils_old/kernelstencils.npz", **stencils)